### ISSUE TITLE
[Android]Crash( 2.14.0) - com.unstoppabledomains.config.client.Client.initClientVersion

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1395]
**Describe the bug**
https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/android:io.gnosis.safe/issues/bfbdf17b74b6cdc0716e2a6424d623ce?time=last-seven-days&sessionEventKey=607D753C00A600013318645C786F6436_1531288814944870899

**To Reproduce**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/e97c3ed1-d9bf-423f-83c9-c8d327dc8fbf)

**Expected behavior**
No crash

**Smartphone (please complete the following information):**
 - Device: Nexus 5X
 - Android Version: 6.0.1
 - App Version 2.14.0

**Environment**
prod mainnet
**Additional context**

**Comment by biafra23** [comment]
This is not the crash that happened ten times, is it?

**Comment by biafra23** [comment]
Stacktrace from Crashlytics:

```
Fatal Exception: java.lang.NoSuchMethodError: No virtual method lines()Ljava/util/stream/Stream; in class Ljava/io/BufferedReader; or its super classes (declaration of 'java.io.BufferedReader' appears in /system/framework/core-libart.jar)
       at com.unstoppabledomains.config.client.Client.initClientVersion(Client.java:22)
       at com.unstoppabledomains.config.client.Client.<clinit>(Client.java:14)
       at com.unstoppabledomains.resolution.contracts.DefaultProvider.getUserAgent(DefaultProvider.java:89)
       at com.unstoppabledomains.resolution.contracts.DefaultProvider.<init>(DefaultProvider.java:30)
       at com.unstoppabledomains.resolution.Resolution$Builder.<init>(Resolution.java:202)
       at com.unstoppabledomains.resolution.Resolution$Builder.<init>(Resolution.java:190)
       at com.unstoppabledomains.resolution.Resolution.builder(Resolution.java:40)
       at io.gnosis.safe.di.modules.RepositoryModule.providesDomainResolutionLibrary(RepositoryModule.java:56)
       at io.gnosis.safe.di.modules.RepositoryModule_ProvidesDomainResolutionLibraryFactory.proxyProvidesDomainResolutionLibrary(RepositoryModule_ProvidesDomainResolutionLibraryFactory.java:32)
       at io.gnosis.safe.di.modules.RepositoryModule_ProvidesDomainResolutionLibraryFactory.provideInstance(RepositoryModule_ProvidesDomainResolutionLibraryFactory.java:22)
       at io.gnosis.safe.di.modules.RepositoryModule_ProvidesDomainResolutionLibraryFactory.get(RepositoryModule_ProvidesDomainResolutionLibraryFactory.java:18)
       at io.gnosis.safe.di.modules.RepositoryModule_ProvidesDomainResolutionLibraryFactory.get(RepositoryModule_ProvidesDomainResolutionLibraryFactory.java:8)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at io.gnosis.safe.di.modules.RepositoryModule_ProvidesUnstoppableRepositoryFactory.provideInstance(RepositoryModule_ProvidesUnstoppableRepositoryFactory.java:29)
       at io.gnosis.safe.di.modules.RepositoryModule_ProvidesUnstoppableRepositoryFactory.get(RepositoryModule_ProvidesUnstoppableRepositoryFactory.java:24)
       at io.gnosis.safe.di.modules.RepositoryModule_ProvidesUnstoppableRepositoryFactory.get(RepositoryModule_ProvidesUnstoppableRepositoryFactory.java:10)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at io.gnosis.safe.ui.dialogs.UnstoppableInputViewModel_Factory.provideInstance(UnstoppableInputViewModel_Factory.java:23)
       at io.gnosis.safe.ui.dialogs.UnstoppableInputViewModel_Factory.get(UnstoppableInputViewModel_Factory.java:18)
       at io.gnosis.safe.ui.dialogs.UnstoppableInputViewModel_Factory.get(UnstoppableInputViewModel_Factory.java:8)
       at io.gnosis.safe.di.ViewModelFactory.create(ViewModelFactory.java:26)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
       at io.gnosis.safe.di.modules.ViewModule.providesUnstoppableInputViewModel(ViewModule.java:91)
       at io.gnosis.safe.di.modules.ViewModule_ProvidesUnstoppableInputViewModelFactory.proxyProvidesUnstoppableInputViewModel(ViewModule_ProvidesUnstoppableInputViewModelFactory.java:40)
       at io.gnosis.safe.di.modules.ViewModule_ProvidesUnstoppableInputViewModelFactory.provideInstance(ViewModule_ProvidesUnstoppableInputViewModelFactory.java:29)
       at io.gnosis.safe.di.modules.ViewModule_ProvidesUnstoppableInputViewModelFactory.get(ViewModule_ProvidesUnstoppableInputViewModelFactory.java:24)
       at io.gnosis.safe.di.modules.ViewModule_ProvidesUnstoppableInputViewModelFactory.get(ViewModule_ProvidesUnstoppableInputViewModelFactory.java:10)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at io.gnosis.safe.di.components.DaggerViewComponent.injectUnstoppableInputDialog(DaggerViewComponent.java:1124)
       at io.gnosis.safe.di.components.DaggerViewComponent.inject(DaggerViewComponent.java:584)
       at io.gnosis.safe.ui.dialogs.UnstoppableInputDialog.inject(UnstoppableInputDialog.java:47)
       at io.gnosis.safe.ui.base.fragment.BaseViewBindingDialogFragment.onAttach(BaseViewBindingDialogFragment.java:19)
       at androidx.fragment.app.Fragment.performAttach(Fragment.java:2672)
       at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:263)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1170)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
       at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
       at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by liliya-soroka** [comment]
Add safe using Unstoppable domain works on prod env in 2.16.0 -2631rc

**Comment by biafra23** [comment]
@liliya-soroka Is this still reproducible?

**Comment by liliya-soroka** [comment]
verified
works in 2.16.0 release
