### ISSUE TITLE
[Android]Crash on prod - DeserializationContext.java line 855

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1398]
**Describe the bug**
https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/android:io.gnosis.safe/issues/8a08756bd6d34c37840b17de86c1bf97?time=last-seven-days&sessionEventKey=607DDFAA0121000121C51B64594D43DA_1531405338255356257

**To Reproduce**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/202891c6-9ec5-40c1-8c6f-82669fe2e101)

**Expected behavior**

**Screenshots**

**Environment**
prod, mainnet
**Additional context**

**Comment by biafra23** [comment]
I contacted JohnnyJumper#6176 on Discord and asked him where I should put the stack traces.

**Comment by biafra23** [comment]
```
Fatal Exception: java.lang.ExceptionInInitializerError
       at com.unstoppabledomains.config.network.NetworkConfigLoader.getContractAddress(NetworkConfigLoader.java:26)
       at com.unstoppabledomains.resolution.naming.service.CNS.<init>(CNS.java:32)
       at com.unstoppabledomains.resolution.Resolution$Builder$2.<init>(Resolution.java:283)
       at com.unstoppabledomains.resolution.Resolution$Builder.build(Resolution.java:282)
       at io.gnosis.safe.di.modules.RepositoryModule.providesDomainResolutionLibrary(RepositoryModule.java:59)
       at io.gnosis.safe.di.modules.RepositoryModule_ProvidesDomainResolutionLibraryFactory.proxyProvidesDomainResolutionLibrary(RepositoryModule_ProvidesDomainResolutionLibraryFactory.java:32)
       at io.gnosis.safe.di.modules.RepositoryModule_ProvidesDomainResolutionLibraryFactory.provideInstance(RepositoryModule_ProvidesDomainResolutionLibraryFactory.java:22)
       at io.gnosis.safe.di.modules.RepositoryModule_ProvidesDomainResolutionLibraryFactory.get(RepositoryModule_ProvidesDomainResolutionLibraryFactory.java:18)
       at io.gnosis.safe.di.modules.RepositoryModule_ProvidesDomainResolutionLibraryFactory.get(RepositoryModule_ProvidesDomainResolutionLibraryFactory.java:8)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at io.gnosis.safe.di.modules.RepositoryModule_ProvidesUnstoppableRepositoryFactory.provideInstance(RepositoryModule_ProvidesUnstoppableRepositoryFactory.java:29)
       at io.gnosis.safe.di.modules.RepositoryModule_ProvidesUnstoppableRepositoryFactory.get(RepositoryModule_ProvidesUnstoppableRepositoryFactory.java:24)
       at io.gnosis.safe.di.modules.RepositoryModule_ProvidesUnstoppableRepositoryFactory.get(RepositoryModule_ProvidesUnstoppableRepositoryFactory.java:10)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at io.gnosis.safe.ui.dialogs.UnstoppableInputViewModel_Factory.provideInstance(UnstoppableInputViewModel_Factory.java:23)
       at io.gnosis.safe.ui.dialogs.UnstoppableInputViewModel_Factory.get(UnstoppableInputViewModel_Factory.java:18)
       at io.gnosis.safe.ui.dialogs.UnstoppableInputViewModel_Factory.get(UnstoppableInputViewModel_Factory.java:8)
       at io.gnosis.safe.di.ViewModelFactory.create(ViewModelFactory.java:26)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
       at io.gnosis.safe.di.modules.ViewModule.providesUnstoppableInputViewModel(ViewModule.java:91)
       at io.gnosis.safe.di.modules.ViewModule_ProvidesUnstoppableInputViewModelFactory.proxyProvidesUnstoppableInputViewModel(ViewModule_ProvidesUnstoppableInputViewModelFactory.java:40)
       at io.gnosis.safe.di.modules.ViewModule_ProvidesUnstoppableInputViewModelFactory.provideInstance(ViewModule_ProvidesUnstoppableInputViewModelFactory.java:29)
       at io.gnosis.safe.di.modules.ViewModule_ProvidesUnstoppableInputViewModelFactory.get(ViewModule_ProvidesUnstoppableInputViewModelFactory.java:24)
       at io.gnosis.safe.di.modules.ViewModule_ProvidesUnstoppableInputViewModelFactory.get(ViewModule_ProvidesUnstoppableInputViewModelFactory.java:10)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at io.gnosis.safe.di.components.DaggerViewComponent.injectUnstoppableInputDialog(DaggerViewComponent.java:1124)
       at io.gnosis.safe.di.components.DaggerViewComponent.inject(DaggerViewComponent.java:584)
       at io.gnosis.safe.ui.dialogs.UnstoppableInputDialog.inject(UnstoppableInputDialog.java:47)
       at io.gnosis.safe.ui.base.fragment.BaseViewBindingDialogFragment.onAttach(BaseViewBindingDialogFragment.java:19)
       at androidx.fragment.app.Fragment.performAttach(Fragment.java:2672)
       at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:263)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1170)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
       at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
       at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:10)
       at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:7)
       at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:1)
       at androidx.test.espresso.base.UiControllerImpl.injectMotionEvent(UiControllerImpl.java:6)
       at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:6)
       at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:1)
       at androidx.test.espresso.action.Tap.sendSingleTap(Tap.java:5)
       at androidx.test.espresso.action.Tap.access$100(Tap.java:1)
       at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:1)
       at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
       at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:4)
       at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:19)
       at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
       at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
       at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by biafra23** [comment]
```
Caused by java.lang.RuntimeException: Couldn't load network config
       at com.unstoppabledomains.config.network.NetworkConfigLoader.initNetworkConfig(NetworkConfigLoader.java:45)
       at com.unstoppabledomains.config.network.NetworkConfigLoader.<clinit>(NetworkConfigLoader.java:19)
       at com.unstoppabledomains.config.network.NetworkConfigLoader.getContractAddress(NetworkConfigLoader.java:26)
       at com.unstoppabledomains.resolution.naming.service.CNS.<init>(CNS.java:32)
       at com.unstoppabledomains.resolution.Resolution$Builder$2.<init>(Resolution.java:283)
       at com.unstoppabledomains.resolution.Resolution$Builder.build(Resolution.java:282)
       at io.gnosis.safe.di.modules.RepositoryModule.providesDomainResolutionLibrary(RepositoryModule.java:59)
       at io.gnosis.safe.di.modules.RepositoryModule_ProvidesDomainResolutionLibraryFactory.proxyProvidesDomainResolutionLibrary(RepositoryModule_ProvidesDomainResolutionLibraryFactory.java:32)
       at io.gnosis.safe.di.modules.RepositoryModule_ProvidesDomainResolutionLibraryFactory.provideInstance(RepositoryModule_ProvidesDomainResolutionLibraryFactory.java:22)
       at io.gnosis.safe.di.modules.RepositoryModule_ProvidesDomainResolutionLibraryFactory.get(RepositoryModule_ProvidesDomainResolutionLibraryFactory.java:18)
       at io.gnosis.safe.di.modules.RepositoryModule_ProvidesDomainResolutionLibraryFactory.get(RepositoryModule_ProvidesDomainResolutionLibraryFactory.java:8)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at io.gnosis.safe.di.modules.RepositoryModule_ProvidesUnstoppableRepositoryFactory.provideInstance(RepositoryModule_ProvidesUnstoppableRepositoryFactory.java:29)
       at io.gnosis.safe.di.modules.RepositoryModule_ProvidesUnstoppableRepositoryFactory.get(RepositoryModule_ProvidesUnstoppableRepositoryFactory.java:24)
       at io.gnosis.safe.di.modules.RepositoryModule_ProvidesUnstoppableRepositoryFactory.get(RepositoryModule_ProvidesUnstoppableRepositoryFactory.java:10)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at io.gnosis.safe.ui.dialogs.UnstoppableInputViewModel_Factory.provideInstance(UnstoppableInputViewModel_Factory.java:23)
       at io.gnosis.safe.ui.dialogs.UnstoppableInputViewModel_Factory.get(UnstoppableInputViewModel_Factory.java:18)
       at io.gnosis.safe.ui.dialogs.UnstoppableInputViewModel_Factory.get(UnstoppableInputViewModel_Factory.java:8)
       at io.gnosis.safe.di.ViewModelFactory.create(ViewModelFactory.java:26)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
       at io.gnosis.safe.di.modules.ViewModule.providesUnstoppableInputViewModel(ViewModule.java:91)
       at io.gnosis.safe.di.modules.ViewModule_ProvidesUnstoppableInputViewModelFactory.proxyProvidesUnstoppableInputViewModel(ViewModule_ProvidesUnstoppableInputViewModelFactory.java:40)
       at io.gnosis.safe.di.modules.ViewModule_ProvidesUnstoppableInputViewModelFactory.provideInstance(ViewModule_ProvidesUnstoppableInputViewModelFactory.java:29)
       at io.gnosis.safe.di.modules.ViewModule_ProvidesUnstoppableInputViewModelFactory.get(ViewModule_ProvidesUnstoppableInputViewModelFactory.java:24)
       at io.gnosis.safe.di.modules.ViewModule_ProvidesUnstoppableInputViewModelFactory.get(ViewModule_ProvidesUnstoppableInputViewModelFactory.java:10)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at io.gnosis.safe.di.components.DaggerViewComponent.injectUnstoppableInputDialog(DaggerViewComponent.java:1124)
       at io.gnosis.safe.di.components.DaggerViewComponent.inject(DaggerViewComponent.java:584)
       at io.gnosis.safe.ui.dialogs.UnstoppableInputDialog.inject(UnstoppableInputDialog.java:47)
       at io.gnosis.safe.ui.base.fragment.BaseViewBindingDialogFragment.onAttach(BaseViewBindingDialogFragment.java:19)
       at androidx.fragment.app.Fragment.performAttach(Fragment.java:2672)
       at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:263)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1170)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
       at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
       at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:10)
       at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:7)
       at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:1)
       at androidx.test.espresso.base.UiControllerImpl.injectMotionEvent(UiControllerImpl.java:6)
       at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:6)
       at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:1)
       at androidx.test.espresso.action.Tap.sendSingleTap(Tap.java:5)
       at androidx.test.espresso.action.Tap.access$100(Tap.java:1)
       at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:1)
       at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
       at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:4)
       at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:19)
       at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
       at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
       at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by biafra23** [comment]
```
Caused by com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "version" (class com.unstoppabledomains.config.network.model.NetworkConfig), not marked as ignorable (one known property: "networks"])
 at [Source: (String)"{
    "version": "1.1.0",
    "networks": {
        "1": {
            "contracts": {
                "Registry": {
                    "address": "0xD1E5b0FF1287aA9f9A268759062E4Ab08b9Dacbe",
                    "legacyAddresses": []
                },
                "SignatureController": {
                    "address": "0x82EF94294C95aD0930055f31e53A34509227c5f7",
                    "legacyAddresses": []
                },
                "MintingController": {
                    "address"[truncated 3440 chars]; line: 2, column: 17] (through reference chain: com.unstoppabledomains.config.network.model.NetworkConfig["version"])
       at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:855)
       at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1212)
       at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1604)
       at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1582)
       at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:299)
       at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
       at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4526)
       at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3468)
       at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3436)
       at com.unstoppabledomains.config.network.NetworkConfigLoader.initNetworkConfig(NetworkConfigLoader.java:43)
       at com.unstoppabledomains.config.network.NetworkConfigLoader.<clinit>(NetworkConfigLoader.java:19)
       at com.unstoppabledomains.config.network.NetworkConfigLoader.getContractAddress(NetworkConfigLoader.java:26)
       at com.unstoppabledomains.resolution.naming.service.CNS.<init>(CNS.java:32)
       at com.unstoppabledomains.resolution.Resolution$Builder$2.<init>(Resolution.java:283)
       at com.unstoppabledomains.resolution.Resolution$Builder.build(Resolution.java:282)
       at io.gnosis.safe.di.modules.RepositoryModule.providesDomainResolutionLibrary(RepositoryModule.java:59)
       at io.gnosis.safe.di.modules.RepositoryModule_ProvidesDomainResolutionLibraryFactory.proxyProvidesDomainResolutionLibrary(RepositoryModule_ProvidesDomainResolutionLibraryFactory.java:32)
       at io.gnosis.safe.di.modules.RepositoryModule_ProvidesDomainResolutionLibraryFactory.provideInstance(RepositoryModule_ProvidesDomainResolutionLibraryFactory.java:22)
       at io.gnosis.safe.di.modules.RepositoryModule_ProvidesDomainResolutionLibraryFactory.get(RepositoryModule_ProvidesDomainResolutionLibraryFactory.java:18)
       at io.gnosis.safe.di.modules.RepositoryModule_ProvidesDomainResolutionLibraryFactory.get(RepositoryModule_ProvidesDomainResolutionLibraryFactory.java:8)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at io.gnosis.safe.di.modules.RepositoryModule_ProvidesUnstoppableRepositoryFactory.provideInstance(RepositoryModule_ProvidesUnstoppableRepositoryFactory.java:29)
       at io.gnosis.safe.di.modules.RepositoryModule_ProvidesUnstoppableRepositoryFactory.get(RepositoryModule_ProvidesUnstoppableRepositoryFactory.java:24)
       at io.gnosis.safe.di.modules.RepositoryModule_ProvidesUnstoppableRepositoryFactory.get(RepositoryModule_ProvidesUnstoppableRepositoryFactory.java:10)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at io.gnosis.safe.ui.dialogs.UnstoppableInputViewModel_Factory.provideInstance(UnstoppableInputViewModel_Factory.java:23)
       at io.gnosis.safe.ui.dialogs.UnstoppableInputViewModel_Factory.get(UnstoppableInputViewModel_Factory.java:18)
       at io.gnosis.safe.ui.dialogs.UnstoppableInputViewModel_Factory.get(UnstoppableInputViewModel_Factory.java:8)
       at io.gnosis.safe.di.ViewModelFactory.create(ViewModelFactory.java:26)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
       at io.gnosis.safe.di.modules.ViewModule.providesUnstoppableInputViewModel(ViewModule.java:91)
       at io.gnosis.safe.di.modules.ViewModule_ProvidesUnstoppableInputViewModelFactory.proxyProvidesUnstoppableInputViewModel(ViewModule_ProvidesUnstoppableInputViewModelFactory.java:40)
       at io.gnosis.safe.di.modules.ViewModule_ProvidesUnstoppableInputViewModelFactory.provideInstance(ViewModule_ProvidesUnstoppableInputViewModelFactory.java:29)
       at io.gnosis.safe.di.modules.ViewModule_ProvidesUnstoppableInputViewModelFactory.get(ViewModule_ProvidesUnstoppableInputViewModelFactory.java:24)
       at io.gnosis.safe.di.modules.ViewModule_ProvidesUnstoppableInputViewModelFactory.get(ViewModule_ProvidesUnstoppableInputViewModelFactory.java:10)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at io.gnosis.safe.di.components.DaggerViewComponent.injectUnstoppableInputDialog(DaggerViewComponent.java:1124)
       at io.gnosis.safe.di.components.DaggerViewComponent.inject(DaggerViewComponent.java:584)
       at io.gnosis.safe.ui.dialogs.UnstoppableInputDialog.inject(UnstoppableInputDialog.java:47)
       at io.gnosis.safe.ui.base.fragment.BaseViewBindingDialogFragment.onAttach(BaseViewBindingDialogFragment.java:19)
       at androidx.fragment.app.Fragment.performAttach(Fragment.java:2672)
       at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:263)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1170)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
       at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
       at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:10)
       at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:7)
       at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:1)
       at androidx.test.espresso.base.UiControllerImpl.injectMotionEvent(UiControllerImpl.java:6)
       at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:6)
       at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:1)
       at androidx.test.espresso.action.Tap.sendSingleTap(Tap.java:5)
       at androidx.test.espresso.action.Tap.access$100(Tap.java:1)
       at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:1)
       at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
       at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:4)
       at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:19)
       at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
       at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
       at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by liliya-soroka** [comment]
The crash on "Unstoppable domain" click during add safe flow.
There is no crash on staging, but the crash appears on the prod ( both rinkeby and mainnet)

**Comment by biafra23** [comment]
I proposed a solution to UD to fix this.

**Comment by liliya-soroka** [comment]
Verified
no crash and no error  in the 2.15.0 -2539 ( prod, rinkeby)
