### ISSUE TITLE
[Android] Crash: HeimdallEncryptionManager.java line 283

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1511]
**Describe the bug**
5 users faced the issue via one day 
https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/android:io.gnosis.safe/issues/29f6c56c8b8313597ee6719133a37544?time=last-seven-days&sessionEventKey=60C843FD0390000133F90AF3525F96F4_1552344471616535734

**To Reproduce**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/c7250339-72f8-492c-aabc-392d9bfbc726)

**Expected behavior**
No crash

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - Android Version: 11
 - App Version 2.17.0 

**Environment**
prod, mainnet
**Additional context**

**Comment by liliya-soroka** [comment]
Verified on emulator :
disable /enable passcode
change passcode

**Comment by liliya-soroka** [comment]
reopened:
the crash appears again on the prod in 2.17.1- 2799 version
https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/android:io.gnosis.safe/issues/29f6c56c8b8313597ee6719133a37544?time=last-seven-days&sessionEventKey=60D333A303160001558569DEDC054F9D_1555422208066858614

**Comment by liliya-soroka** [comment]
Unfortunatly the issue still exists in 2.18.0 ![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/d7c15dc3-bd41-4547-8026-89f1481e949e)

**Comment by biafra23** [comment]
This is the underlying cause:
```
Caused by java.lang.IllegalStateException: At least one biometric must be enrolled to create keys requiring user authentication for every use
       at android.security.keystore.KeymasterUtils.addSids(KeymasterUtils.java:288)
       at android.security.keystore.KeymasterUtils.addUserAuthArgs(KeymasterUtils.java:352)
       at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.initialize(AndroidKeyStoreKeyPairGeneratorSpi.java:386)
       at java.security.KeyPairGenerator$Delegate.initialize(KeyPairGenerator.java:697)
       at java.security.KeyPairGenerator.initialize(KeyPairGenerator.java:438)
       at io.gnosis.data.security.HeimdallEncryptionManager.getOrCreateKey(HeimdallEncryptionManager.java:283)
       at io.gnosis.data.security.HeimdallEncryptionManager.getInitializedRSACipherForEncryption(HeimdallEncryptionManager.java:210)
       at io.gnosis.safe.ui.settings.app.passcode.PasscodeViewModel.encryptPasscodeWithBiometricKey(PasscodeViewModel.java:163)
       at io.gnosis.safe.ui.settings.app.passcode.RepeatPasscodeFragment$onViewCreated$1$2.invoke(RepeatPasscodeFragment.java:87)
```

But: Before calling this we check `BiometricManager.BIOMETRIC_SUCCESS` which is supposed to mean that fingerprints are enrolled. So this seems to be a bug on the device side.

**Comment by liliya-soroka** [comment]
Closed.
I will check if it appears after 3.0.0 release.
But if it's a device issue I think we may skip it
