### ISSUE TITLE
Unable to resume activity {io.gnosis.safe.rinkeby/io.gnosis.safe.ui.splash.SplashActivity}

### ISSUE THREAD

**Issue by biafra23** [gnosis/safe-android#960]
Crash from Crashlytics (**Rinkeby**): 
https://console.firebase.google.com/u/0/project/safe-firebase-rinkeby/crashlytics/app/android:io.gnosis.safe.rinkeby/issues/c212ad80db3fc0b22b33dacfac8f04a1?time=last-seven-days&sessionEventKey=5F6DBA5D03D200016F3507E2E3F23F59_1454802826584321539

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {io.gnosis.safe.rinkeby/io.gnosis.safe.ui.splash.SplashActivity}: java.lang.IllegalStateException: Fragment already added: TermsBottomSheetDialog{b133910} (45a0e12a-11bd-4065-8f81-2724592ba8b6) TermsBottomSheetDialog}
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3919)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3951)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6863)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
- Device: OnePlus 6
- Android OS version: 9
- Safe app version: 2.1.0-1072-rinkeby

**Comment by DmitryBespalov** [comment]
fixed
